[nixpacks]
version = "1.24.0"

[phases.setup]
nixPkgs = ["nodejs_18", "python311"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"