name: Deploy Project to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: 📦 Install Railway CLI
        run: npm install -g @railway/cli

      - name: 🔐 Inject Railway Token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "Token injetado com sucesso."

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔨 Build project
        run: npm run build

      - name: 🚀 Deploy to Railway
        run: railway up
